### ISSUE TITLE
Regarding  VASP2WANNIER  Spn file

### ISSUE THREAD

**Issue by suneetha98** [Chengcheng-Xiao/VASP2WAN90_v2_fix#11]
In the vasp2wannier calculation. I am using vasp6.3 with wannier90-developer code
I am trying to calculate the spin hall conductivity when I am running postw90.x  it is showing an error in opening input file  wannier90.spn. 
But vasp6.3.0 is not generating wannier90.spn file
so I used vasp5.4  with wannier to generate the wannier90.spn file after that I ran vasp6.3 with wannier but it is showing 
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Please suggest me, how to resolve this problem.
Thank you in advance

**Comment by Chengcheng-Xiao** [comment]
The error you gave:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```
is ambiguous as the root cause cannot be determined directly from it. 

Since this error is produced by VASP v6.3.0, I cannot help you with it. This repo only provides fix to VASP v5.4.4 so all calculations done with this patch should be performed using VASP v5.4.4. No other version of VASP is supported.

For the purpose of calculating spin hall conductivity, I would suggest checking out [example 3](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix/tree/dev/example/example3). In the meantime, it would also be helpful if you can give [the wiki](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix/wiki) a read.

**Comment by suneetha98** [comment]
Because I was using the SCDM method which is implemented in vasp6.3
I continued the calculation with vasp6.3.0
I will try with the vasp5.4.4 
thank you for your reply.

**Comment by suneetha98** [comment]
Dear Sir,
I kindly request you to clarify some of my doubts related to Wannier function.
1. Is it possible to get real Wannier functions, when spin orbit coupling taken into account ? If not,  how to check the convergence of the Wannier functions ?
 2. The kmesh used in the DFT computation affects the plateau of the spin Hall conductivity. Is there any different method  to confirm  the spin Hall conductivity plateau.(how to check obtained spin Hall conductivity plateau  is correct or not ?)
Thank you in advance

**Comment by Chengcheng-Xiao** [comment]
I don't think this is a good place for such questions as they are not related to the code itself. In the meantime, as I'm not an expert on the topics that you mentioned, I would suggest you send an email with your questions to the [🔗 official mailing list](https://wannier.org/support/#:~:text=Community%20Email%20Forum&text=Once%20subscribed%2C%20post%20to%20the,posts%20to%20the%20mailing%20list.).

**Comment by suneetha98** [comment]
Thank you Sir for your suggestion.
